function ahome_pages_clientio(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',Kb='&',oc='.cache.html',db='/',pb='//',dc='0D658EB851E1822E155D24B3C28580FD',jc='39BB845BEA45EFCC2B4D6982AD686CDF',kc='4D91909845A5CBA195D3AEE357F1E194',lc='5D98656C0F11BD6A817D50E266ABEB55',nc=':',ec=':1',fc=':2',gc=':3',hc=':4',ic=':5',tb='::',Fc='<script defer="defer">ahome_pages_clientio.onInjectionDone(\'ahome_pages_clientio\')<\/script>',lb='<script id="',xc='<script language="javascript" src="',wb='=',cb='?',mc='B1A13C061E2F5E81FA488DDDD1F0AA3E',yb='Bad handler "',vc='DOMContentLoaded',wc='Detect_min.js',yc='Detect_min.js"><\/script>',Bc='FABridge.js',Cc='FABridge.js"><\/script>',nb='SCRIPT',kb='__gwt_marker_ahome_pages_clientio',U='ahome_pages_clientio',ib='ahome_pages_clientio.nocache.js',sb='ahome_pages_clientio::',Rb='android',Gb='applicationType',ob='base',gb='baseUrl',X='begin',W='bootstrap',fb='clear.cache.gif',Dc='clientio/ClientIO.swf',Ec='clientio/ClientIO.swf"><\/script>',vb='content',Lb='desktop',Ib='device',ab='end',Jb='formfactor',Zb='gecko',$b='gecko1_8',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',uc='head',bc='hosted.html?ahome_pages_clientio',tc='href',Wb='ie10',Yb='ie8',Xb='ie9',Cb='iframe',eb='img',Qb='ipad',Ob='iphone',Pb='ipod',Db="javascript:''",qc='link',ac='loadExternalRefs',qb='meta',Fb='moduleRequested',_='moduleStartup',Vb='msie',rb='name',pc='notification/notification.css',Mb='phone',Eb='position:absolute;width:0;height:0;border:none',rc='rel',Ub='safari',hb='script',cc='selectingPermutation',V='startup',sc='stylesheet',zc='swfobject-2.0.js',Ac='swfobject-2.0.js"><\/script>',Nb='tablet',jb='undefined',_b='unknown',Sb='user.agent',Hb='web',Tb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}ahome_pages_clientio=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=J(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a){var b=u[a];return b==null?null:b}
function K(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){if(typeof m!=jb||typeof window!=jb){return Hb}else{return Ib}};v[Gb]={device:0,web:1};w[Jb]=function(){var a=location.search;var b=a.indexOf(Jb);if(b>=0){var c=a.substring(b);var d=c.indexOf(wb)+1;var e=c.indexOf(Kb);if(e==-1){e=c.length}var f=c.substring(d,e);if(f!=Lb&&(f!=Mb&&f!=Nb)){f=Lb}return f}var g=navigator.userAgent.toLowerCase();if(g.indexOf(Ob)!=-1||g.indexOf(Pb)!=-1){return Mb}else if(g.indexOf(Qb)!=-1){return Nb}else if(g.indexOf(Rb)!=-1||g.indexOf(Mb)!=-1){var h=160;var i=m.screen.width/h;var j=m.screen.height/h;var k=Math.sqrt(i*i+j*j);return k<6?Mb:Nb}return Lb};v[Jb]={desktop:0,phone:1,tablet:2};w[Sb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Tb)!=-1}())return Ub;if(function(){return b.indexOf(Vb)!=-1&&n.documentMode>=10}())return Wb;if(function(){return b.indexOf(Vb)!=-1&&n.documentMode>=9}())return Xb;if(function(){return b.indexOf(Vb)!=-1&&n.documentMode>=8}())return Yb;if(function(){return b.indexOf(Zb)!=-1}())return $b;return _b};v[Sb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};ahome_pages_clientio.onScriptLoad=function(){if(M){r=true;G()}};ahome_pages_clientio.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:ac,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=bc;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:cc});if(!F()){try{K([Ib,Lb,$b],dc);K([Ib,Mb,$b],dc+ec);K([Ib,Nb,$b],dc+fc);K([Hb,Lb,$b],dc+gc);K([Hb,Mb,$b],dc+hc);K([Hb,Nb,$b],dc+ic);K([Ib,Lb,Ub],jc);K([Ib,Mb,Ub],jc+ec);K([Ib,Nb,Ub],jc+fc);K([Hb,Lb,Ub],jc+gc);K([Hb,Mb,Ub],jc+hc);K([Hb,Nb,Ub],jc+ic);K([Ib,Lb,Xb],kc);K([Ib,Mb,Xb],kc+ec);K([Ib,Nb,Xb],kc+fc);K([Hb,Lb,Xb],kc+gc);K([Hb,Mb,Xb],kc+hc);K([Hb,Nb,Xb],kc+ic);K([Ib,Lb,Yb],lc);K([Ib,Mb,Yb],lc+ec);K([Ib,Nb,Yb],lc+fc);K([Hb,Lb,Yb],lc+gc);K([Hb,Mb,Yb],lc+hc);K([Hb,Nb,Yb],lc+ic);K([Ib,Lb,Wb],mc);K([Ib,Mb,Wb],mc+ec);K([Ib,Nb,Wb],mc+fc);K([Hb,Lb,Wb],mc+gc);K([Hb,Mb,Wb],mc+hc);K([Hb,Nb,Wb],mc+ic);O=A[L(Gb)][L(Jb)][L(Sb)];var Q=O.indexOf(nc);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+oc}catch(a){return}}var R;function S(){if(!s){s=true;if(!__gwt_stylesLoaded[pc]){var a=n.createElement(qc);__gwt_stylesLoaded[pc]=a;a.setAttribute(rc,sc);a.setAttribute(tc,t+pc);n.getElementsByTagName(uc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(vc,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener(vc,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:ac,millis:(new Date).getTime(),type:X});if(!__gwt_scriptsLoaded[wc]){__gwt_scriptsLoaded[wc]=true;document.write(xc+t+yc)}if(!__gwt_scriptsLoaded[zc]){__gwt_scriptsLoaded[zc]=true;document.write(xc+t+Ac)}if(!__gwt_scriptsLoaded[Bc]){__gwt_scriptsLoaded[Bc]=true;document.write(xc+t+Cc)}if(!__gwt_scriptsLoaded[Dc]){__gwt_scriptsLoaded[Dc]=true;document.write(xc+t+Ec)}n.write(Fc)}
ahome_pages_clientio();